Add argument to specify which module gets feature report
M4rc311o/modpadctrl pull request #2
Opened 2024-09-21 08:53 UTC by Kody420

2024-09-22 16:55 UTC, M4rc311o requested changes

2024-09-22 16:55 UTC, M4rc311o commented on modpad_service/src/main.rs
> +        log::info!("{:?}",sliders_data);
Is this *logging* still needed to be part of the code? If so, is there any way to do it without spamming the log so much? If it is supposed to be there in this form at least make it a `log::debug!`.

2024-09-22 16:55 UTC, M4rc311o commented on src/lib.rs
> +}
I am not sure if making *enum* is neccessary when modules are named *ModuleX* (*X* being just a number), and not something dynamically assigned to where correct module is connected. And even if this is the case `#[repr(u8)]` attribute can be used to assign numbers to individual *enum* variants and than all `match module` blocks can be substituted with `module as u8` expression.

2024-09-23 20:03 UTC, Kody420 commented on modpad_service/src/main.rs
> +        log::info!("{:?}",sliders_data);
Removed it but could be nice to activate it with config or something like that.

2024-09-24 13:28 UTC, M4rc311o commented on modpad_service/src/main.rs
> +        log::info!("{:?}",sliders_data);
Ok, *env_logger* crate used in this  project uses `RUST_LOG` environment varible to set a filter level. So logger can be initialized without the filter level (`env_logger::init();`) and than just use `RUST_LOG` varible to set the filter level. Feel free to create PR with this change implemented. Check [this](https://docs.rs/env_logger/latest/env_logger/index.html) for reference.

2024-09-24 13:43 UTC, M4rc311o commented on src/lib.rs
> +}
As underlying code is depending on values assigned to individual *enum* kinds and also to improve code readability. I would suggest to explicitly assign value to each kind. Suggestion below should be correct, but it is not tested.

```suggestion
#[derive(Clone, ValueEnum, Debug)]
#[repr(u8)]
pub enum Module {
    Modpad = 0x00,
    Down = 0x01,
    Left = 0x02,
    Right = 0x03,
}
```

2024-09-24 16:20 UTC, merged